# Generated by Django 4.0.5 on 2024-02-25 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'managed': True, 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelTable(
            name='product',
            table='',
        ),
    ]
